language: csharp
mono: 5.12.0
dotnet: 2.2.101
matrix:
  include:
    - name: "Linux Qt 5.11.1"
      os: linux
      dist: xenial
      sudo: required
      services: docker
    - name: "OSX Qt 5.11.1"
      os: osx
      osx_image: xcode9.4
cache:
    directories:
     - build/Qt
if: tag IS blank
git:
  depth: false
services:
  - docker
script:
  - ./build/travis.sh